services:
  frontend:
    build:
      context: ./timesheet-front
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - my_network
  # backend:
  #   build:
  #     context: ./timesheet
  #   restart: unless-stopped
  #   ports:
  #     - "${BACKEND_PORT}:42131"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - my_network
  #   environment:
  #     PORT: '${PORT}'
  #     PG_HOST: "${PG_HOST}"
  #     PG_PORT: "${PG_PORT}"
  #     PG_USERNAME: "${PG_USERNAME}"
  #     PG_PASSWORD: "${PG_PASSWORD}"
  #     PG_DATABASE: "${PG_DATABASE}"
  #     TG_API_TOKEN: "${TG_API_TOKEN}"
  #     TG_CHAT_ID: "${TG_CHAT_ID}"
  postgres:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: "${PG_USERNAME}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      PG_DATABASE: ${PG_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - my_network
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    depends_on:
      - postgres
    networks:
      - my_network
networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
