user nginx;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout 65;

    # Настройки для CORS (если необходимо)
    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Credentials' 'true';
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
    add_header 'Access-Control-Allow-Headers' 'X-Requested-With,Accept,Content-Type, Origin';

    # HTTP сервер для перенаправления на HTTPS
    server {
        listen 80;
        server_name goldrekrut.ru www.goldrekrut.ru;  # Указываете ваше доменное имя

        # Перенаправление всех запросов на HTTPS
        return 301 https://$host$request_uri;
    }

    # HTTPS сервер
    server {
        listen 443 ssl;
        server_name goldrekrut.ru www.goldrekrut.ru;  # Указываете ваше доменное имя

        # Пути к сертификатам (замените на свои)
        ssl_certificate /etc/ssl/goldrekrut.ru.crt;  # Путь к вашему сертификату
        ssl_certificate_key /etc/ssl/goldrekrut.ru.key;  # Путь к вашему ключу
        
        # Оптимизация безопасности SSL
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';
        ssl_prefer_server_ciphers on;

        # Прокси для API
        location /api {
            proxy_pass http://backend:42131;  
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Обработка фронтенда (например, для SPA)
        location / {
            index  index.html;
            try_files $uri $uri/ /index.html;
            root   /app;  # Директория с фронтендом
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }

    # Дополнительные настройки и сервера (если нужны)
}
