name: Deploy to VPS

on:
    push:
        branches:
            - master # Измени на нужную ветку, если нужно

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy via SSH
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd ${{ secrets.PATH_TO_PROJECT_PROD }}
                      git restore .
                      git pull origin main
                      docker-compose up --build -d
